# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: psyche-echo
spec:
  enabled: true
  requires: ">=2.23.0"
  author:
    name: miany
    website: https://gitee.com/Little-Mianyang
  logo: logo.png
  homepage: https://gitee.com/Little-Mianyang/psyche-echo#readme
  repo: https://gitee.com/Little-Mianyang/psyche-echo
  issues: https://gitee.com/Little-Mianyang/psyche-echo/issues
  displayName: "心灵回响"
  description: "记录日记、记录心情、想法和生活点滴"
  license:
    - name: "GPL-3.0"
      url: "https://gitee.com/Little-Mianyang/psyche-echo/blob/main/LICENSE"
  extensionPoints:
    console:
      uiPlugins:
        - entry: main.js